name: Merge PR Accepted

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch you would like to run the CI/CD pipeline on'

# update repository code inside the branch etc.


env:
  