# Merge PR Accepted or Manual Trigger
name: Integration

on:
  # pushes to master cannot occur without merge PR being accepted
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch you would like to run the CI/CD pipeline on?'
        required: false
        type: string
        default: 'main'
      performance-test:
        description: 'Would you like to run a performance test on the container?'
        required: false
        default: true
        type: bool
      deployment: 
        description: 'Would you like to review the performance report before updating the official image?'
        required: false
        default: true
        type: bool
      comments:
        description: 'Add any comments which can be added as annotations to the workflow run and container image/test reports'
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  copying_branch:
    runs-on: nvidia-jetson
    steps:
        - name: Checkout branch
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.inputs.branch }}
        - name: Print branch
          run: echo "Checked out branch: ${{ github.event.inputs.branch || 'main' }}"
  
  delivery:
    runs-on: nvidia-jetson
    needs: copying_branch
    outputs:
      container_name: ${{ steps.delivery.outputs.container_name }}
      artifact_id: ${{ steps.delivery.outputs.artifact_id }}
    steps:
      - name: Call delivery workflow
        id: delivery
        uses: ./.github/workflows/delivery.yml
        with:
          branch: ${{ github.event.inputs.branch || 'main' }}

  deployment:
    runs-on: nvidia-jetson
    needs: delivery
    outputs:
      
    uses: ./github/workflows/deployment.yml
    with:
      performance-test: ${{ github.event.inputs.performance-test }}
      deployment: ${{ github.event.inputs.deployment }}
      container_name: ${{ needs.delivery.outputs.container_name }}
      artifact_id: ${{ needs.delivery.outputs.artifact_id }}