name: Issue Progress Reporting
on:
  workflow_call:
      inputs:
        status:
          required: true
          type: string
  workflow_dispatch:
    # enter separate questions here...
    inputs: 
      status:
        required: true
        type: choice
        options:
        - error


jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue create --title "My new issue" --body "Here are more details."
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage